### ISSUE TITLE
[DEBIAN] Background music keeps on playing

### ISSUE THREAD

**Issue by AreYouLoco** [SecUpwN/Spotify-AdKiller#102]
i am Using Debian Stable Stretch and Spotify 1.0.64.407.g9bd02c2d.
I have installed all dependencies.

It seems like the ad is muted properly and the local music is playing instead but during the ad and after ad finishes the background music keeps playing. no vlc interface tho. I have to kill it manually with killall vlc.

**Comment by targetcreature** [comment]
I'm also having this experience.

Ubuntu 17.10, Spotify 1.0.64.407.g9bd02c2d
