### ISSUE TITLE
No support for pipewire

### ISSUE THREAD

**Issue by hamburg1r** [SecUpwN/Spotify-AdKiller#128]
So, I was trying to use spotify-adkiller in endeavour os which uses pipewire instead of pulseaudio and doesn't have pacmd. How can I use it without pacmd?

**Comment by bashified** [comment]
I am running pipewire on debian 11 bookworm and it seems to work fine for me, are u sure the issue is pipewire?

**Comment by hamburg1r** [comment]
It has been 3 years. I don't see myself using it anymore.

**Comment by bashified** [comment]
lmao okay
