### ISSUE TITLE
Error: Spotify not found

### ISSUE THREAD

**Issue by zsteinmetz** [SecUpwN/Spotify-AdKiller#20]
Since yesterday, AdKiller doesn't manage to find the Spotify runtime, so that ads remain unblocked. I've already pulled the latest git. Maybe Spotify has changed anything in their way of treating songs?
Unfortunately, I haven't had the time to dig deeper. Any ideas?

// Running on Ubuntu 14.10, Spotify 0.9.11.27

**Comment by kodzak** [comment]
Yes, they did. They change name of window from "Spotify - Linux Preview" to "Spotify Free - Linux Preview". But unfortunately the change something else and app doesn't block ads.

**Comment by kodzak** [comment]
Any idea what more change or this is all and my script don't work... ?

**Comment by kodzak** [comment]
Good still working i forget change name in other file. I don't check other script spotify-adkiller. :)

**Comment by philippeluickx** [comment]
+1

**Comment by zsteinmetz** [comment]
Okay, the workaround is to change WMTITLE="Spotify - Linux Preview" to WMTITLE="Spotify Free - Linux Preview" in <b>both</b> spotify-adkiller.sh and (line 44) and the wrapper script (line 41)

**Comment by OlegSmelov** [comment]
@zsteinmetz :+1: 

I'll update the script tomorrow or the day after. Until then, use this workaround.

**Comment by SecUpwN** [comment]
Welcome to Spotify-AdKiller, @zsteinmetz! I see that @OlegSmelov has already reviewed your pull requests - thank you for your awesome commitment here! I have helped @leamas to solve the Issue where it says "[GCRYPT_1.2 not found](https://github.com/leamas/spotify-make/issues/40)" - can you test his feature branch so that it will finally be merged?

**Comment by Feltzer** [comment]
Thanks for the bug report, @zsteinmetz.

For the time being I've put together a solution and pushed it to [a new branch](https://github.com/SecUpwN/Spotify-AdKiller/commit/1c205635a83193f45e1b8771a99168abaffa5cff). I don't think it's as elegant as it could be, but it does its job. I've added some documentation to the README to account for the changes.

Would love to hear your thoughts on this solution, guys.

**Comment by Feltzer** [comment]
As per the discussion on #21, I've merged the two pull requests by @zsteinmetz. Spotify-AdKiller should be able to find the Spotify again now. Thanks for helping us track this down, guys!
