### ISSUE TITLE
Modifications to cfg file don't have effect

### ISSUE THREAD

**Issue by rafa10pj** [SecUpwN/Spotify-AdKiller#29]
AdKiller is working fine for me as is, but I've been meaning to change some of the options in the cfg file.

Mind you, I'm new to Linux so this might be a stupid oversight on my part, but I can't seem to be able to change AdKiller's behavior when changing the .cfg file. Specifically, I've tried changing mode by setting

`CUSTOM_MODE="simple"`

The local music folder by setting

`CUSTOM_MUSIC="/mnt/00DCCC3679CC023C/Música/Toro Y Moi"`

And no alert by setting 

`CUSTOM_ALERT="none"`

None of these seem to work, so I must be doing something wrong.

**Comment by SecUpwN** [comment]
Good evening @rafa10pj and welcome to our project on GitHub! :+1:

@Feltzer, I cannot see any error on his part, is this a bug in our script? What do you recommend?

**Comment by rafa10pj** [comment]
Hey @SecUpwN, I use Ubuntu 14.04. And thanks! This is a great little solution for Spotify.

**Comment by SecUpwN** [comment]
>And thanks! This is a great little solution for Spotify.

You may press the `Star` button if you like it. :) Let's wait for @Feltzer to answer..

**Comment by rafa10pj** [comment]
I've not been able to sit down at my desk to check the logfile, will do ASAP, @SecUpwN.

**Comment by Feltzer** [comment]
Hi @rafa10pj,

thanks for posting a bug report. Are you sure you are modifying the right configuration file (not the one in the download folder, but the one at `~/.config/Spotify-AdKiller/Spotify-AdKiller.cfg`)?

**Comment by rafa10pj** [comment]
Hey @Feltzer,

I can only find one configuration file in my computer and it's in ```/home/rafael/Spotify-AdKiller```. I believe I deleted the download files long ago.

**Comment by SecUpwN** [comment]
>I deleted the download files long ago.

@rafa10pj, please re-download all files properly and re-verify this Issue. Thanks.

**Comment by rafa10pj** [comment]
Okay, I just noticed that I was modifying is the .cfg file that's created when the git is cloned. Where should I find the proper .cfg file? It's not where the 2 .sh files are in ```/home/rafael/bin```

**Comment by Feltzer** [comment]
That's fine. I am glad you figured it out :). Have fun with Spotify AdKiller! 

I will close this now.
