### ISSUE TITLE
~/bin/spotify-wrapper.sh closes as soon as spotify loads?

### ISSUE THREAD

**Issue by nathanurwin** [SecUpwN/Spotify-AdKiller#34]
Ads are not being muted, I'm on `Linux xyz 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux` with Spotify `Version 0.9.17.1.g9b85d436`. I believe the adkiller script is closing as soon as Spotify loads for some reason?

    user@home:~$ bash ~/bin/spotify-wrapper.sh
    ## Waiting for Spotify ##
    ## Waiting for Spotify ##
    DEBUG mode active
    user@home:~$ _

**Comment by raphael-costa** [comment]
Did you install Pulseaudio? It's not tagged as a dependency in the AURfor some reason

**Comment by trinaldi** [comment]
Check the above mentioned, if that doesn't help,I 'm not sure if I'll be able to. But I'm running the latest (testing `1:1.0.15.137.gbdf68615`) version of Spotify with the DNS block.

One thing I had to change in the `spotify-wrapper.sh` file was the line 41:
> WMTITLE="Spotify Free - Linux Preview"

to

> WMTITLE="Spotify"

Otherwise I'd get the message "Error: Spotify not found."

Also, I really recommend the DNS block, it's very effective. One thing I miss is the lyrics, I'm sure it's just a case to put the URL in the whitelist.

**Comment by nateurwin** [comment]
@raphael-costa Yes, I have pulseaudio and the other dependencies installed.
@trinaldi What is the DNS block?

To be honest I gave up on trying to get this to work, and have been using this [gist](https://gist.github.com/pcworld/3198763/#gistcomment-857143). It would be nice to not have to run a terminal in the background everytime I want to listen to music though.

**Comment by trinaldi** [comment]
CHeck this branch:
https://github.com/SecUpwN/Spotify-AdKiller/tree/dns-block

**Comment by SecUpwN** [comment]
@nathanurwin, is your question here solved now?

**Comment by nathanurwin** [comment]
@SecUpwN Yeah, you can close this issue. I use mplayer in a terminal for music now.

**Comment by SecUpwN** [comment]
>I use mplayer in a terminal for music now.

Does that work with `Spotify-AdKiller`, or did you ditch our script?

**Comment by nathanurwin** [comment]
@SecUpwN
> Does that work with `Spotify-AdKiller`
No, I stopped using `Spotify-Adkiller`, but just because I really stopped using spotify. I have a hunch the script was just installed incorrectly, since I was on debian and not ubuntu so feel free to close this issue.
