### ISSUE TITLE
Spotify ads came back

### ISSUE THREAD

**Issue by dokker** [SecUpwN/Spotify-AdKiller#36]
Is it posible that the ads can't be blocked anymore? How can I help to investigate what happened?

**Comment by OlegSmelov** [comment]
Did you update Spotify?

**Comment by dokker** [comment]
Yes I updated recently ( to 0.9.11.27)
Unfortunately I can't attach my log file here. 
Log: https://gist.github.com/545586126036071fe5f7.git

**Comment by dokker** [comment]
The Issue gone away after rebooting. It semms the problem related to my system and upgrade.
