### ISSUE TITLE
wmctrl: missing dependencies

### ISSUE THREAD

**Issue by Nhoya** [SecUpwN/Spotify-AdKiller#40]
Hey there, at line 562 of `spotify-adkiller.sh`:
```
done < <(xprop -spy -id $(wmctrl -lx | awk -F' ' '$3 == "spotify.Spotify" {print $1}') _NET_WM_NAME)
```
wmctrl is not a default utility so please add it to dependecies list  ty :+1:

**Comment by SecUpwN** [comment]
Good evening @Nhoya, is this actually a dupe of #39? I'll add the dependency soon, stay tuned.
