### ISSUE TITLE
Debug is logging only first track and exit status

### ISSUE THREAD

**Issue by Nhoya** [SecUpwN/Spotify-AdKiller#41]
Hey there, i'm trying to use debug but it logs only the first track and the exit status.. really not understanding why.. some advice?

I'm using Spotify 0.9.17.1 on debian

I'm trying to use debug because the ads are not being muted anymore and i'm trying to understand why

**Comment by SecUpwN** [comment]
@Feltzer, would you help him, please? Thanks a lot!

**Comment by Nhoya** [comment]
@SecUpwN Gotcha! the problem is the same exposed here https://github.com/SecUpwN/Spotify-AdKiller/issues/37 after the commit 6b6252c something went wrong for older versions i think it need an hard fix or just a branch for old-stable version of spotify( 0.9.17.1 ) 
P.S. 
i think we can close it and link to the other one!
