### ISSUE TITLE
Verify Similar Projects

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Spotify-AdKiller#44]
Good evening, @Feltzer! I would like to know if we should keep the [Similar Projects](https://github.com/SecUpwN/Spotify-AdKiller#similar-projects) in our `README` or if we should add those to a separate WIKI entry (in that case I'd need to create our WIKI first). Reason for this discussion is that I do not want outdated or invalid projects to be recommended in our project `README`, which could lead users into installing non-working crap. Let me know your thoughts here.

**Comment by Feltzer** [comment]
Yeah, some seem to be unmaintained. We should probably remove spotimute and indicator-muteads from the list, as both of these haven't seen an update in years.

As for the wiki, I don't think that's necessary. It would be fairly empty with only an entry for links to similar projects. I think we should keep this in the README, as long we check to make sure that the other projects are maintained every now and then.

**Comment by SecUpwN** [comment]
Thanks @Feltzer, I have just removed the projects you mentioned, but in the long run, we're likely not able to maintain a current list of working projects since there are simply [too many](https://github.com/search?utf8=%E2%9C%93&q=spotify+mute). So what to do in the long term?

**Comment by Feltzer** [comment]
True, but I think we should take that as it comes. The three projects we link to are well maintained and working. We don't have to add any new project that comes along to the list, just keep an eye on these three as they follow three entirely different ad blocking methods (dbus-based, stdout-based, blocklist-based).

**Comment by SecUpwN** [comment]
>True, but I think we should take that as it comes.

You're right. Feel invited to add other projects you think are worth being listed there.

> We don't have to add any new project that comes along to the list, just keep an eye on these three as they follow three entirely different ad blocking methods (dbus-based, stdout-based, blocklist-based).

Perfect, will do so. Issue clarified (at least in my head) for now. Thank you!
