### ISSUE TITLE
Doesn't name missing dependencies

### ISSUE THREAD

**Issue by hcgrove** [SecUpwN/Spotify-AdKiller#51]
When I try to run the install script, this is what happens:
grove@solitaire> ./install.sh
 not found
Please resolve these dependency errors before running the script

Manually checking the listed dependencies, revealed that I missed xdotool, and installing that brought me further.

**Comment by Feltzer** [comment]
Thanks for reporting this!

I think I found the issue. I'll push a commit in a sec which should fix this.

**Comment by SecUpwN** [comment]
>I think I found the issue. I'll push a commit in a sec which should fix this.

Huge thanks, wonderful that you're our `COLLABORATOR`! :smile_cat:
