### ISSUE TITLE
Song falsely detected as Ad

### ISSUE THREAD

**Issue by datamaan** [SecUpwN/Spotify-AdKiller#57]
This song: https://open.spotify.com/track/061joO5eUg78KlNJIkMt0o
is falsely detected as Ad because it produces the following values which are not equal:

XPROP_DEBUG: Céline Dion - My Heart Will Go On - Love Theme from \"Titanic\"
DBUS_DEBUG:  Céline Dion - My Heart Will Go On - Love Theme from "Titanic"

**Comment by SecUpwN** [comment]
@datamaan, you Issue should be fixed now thanks to the great help of @mikar. Please test if it works.
