### ISSUE TITLE
Most Indian songs are marked as ads

### ISSUE THREAD

**Issue by shivamkalra** [SecUpwN/Spotify-AdKiller#64]
I'm not exactly sure, how are you detecting ads from regular songs.

However, most Indian songs are marked as ads and mute my pulse audio channel.

I can help to fix the issue, if you can help me where to begin.

**Comment by SecUpwN** [comment]
>However, most Indian songs are marked as ads and mute my pulse audio channel.

Good morning @shivamkalra. Please add a logfile to this Issue using these instructions:

>You can make the CLI output more verbose and enable the log file by setting `DEBUG` to `1`. The log will be written to `$HOME/.Spotify-AdKiller.log` and replaced each time `Spotify-AdKiller` runs.

**Comment by shivamkalra** [comment]
I tried `DEBUG=1 spotify-wrapper.sh` but it did not go in debug mode. However, I just removed if statements to make it always debug. I'm attaching log file.



[log.txt](https://github.com/SecUpwN/Spotify-AdKiller/files/256903/log.txt)

**Comment by OlegSmelov** [comment]
@shivamkalra I have a fix in a feature branch that might fix this problem: https://github.com/SecUpwN/Spotify-AdKiller/tree/switch-detection-method

Let me know if it works!

**Comment by OlegSmelov** [comment]
Pretty sure this should now be fixed.
