### ISSUE TITLE
Provide uninstall script

### ISSUE THREAD

**Issue by igniting** [SecUpwN/Spotify-AdKiller#70]
Provide a script to remove Spotify-AdKiller or give detailed instructions in README.

**Comment by zppinto** [comment]
To uninstall just execute this command:
`rm -Rf ~/.installer-spotify-ad-killer ; sudo rm -Rf  /usr/local/bin/dns-block ; sudo rm -f /usr/local/bin/spotify-wrapper.sh ; sudo rm -f /usr/local/bin/spotify-adkiller.sh ; rm -f ~/.local/share/applications/Spotify\ \(AdKiller\).desktop
`
