### ISSUE TITLE
For Microsoft Windows

### ISSUE THREAD

**Issue by Apttypn** [SecUpwN/Spotify-AdKiller#82]
i added some files from this repository and i was able to make it work even BETTER on windows. i hope you can add it here aswell!

**Comment by OlegSmelov** [comment]
@Apttypn Can you explain what exactly you did? I won't hide that I'm very skeptical about this working on anything other that Linux. 😄

**Comment by Apttypn** [comment]
@OlegSmelov I used the Adkiller.cfg and the adkiller.sh and deleted ad.spa from Spotify/apps folder and i have had no ads

**Comment by Apttypn** [comment]
i renamed the *.sh to *.cfg and it works like a charm :)

**Comment by OlegSmelov** [comment]
> deleted ad.spa from Spotify/apps

This might have been it. But adding files into Spotify directory should have had no effect whatsoever.

I don't think `Spotify-AdKiller` is even running on your machine.
