### ISSUE TITLE
dns-block is blocking playlist covers.

### ISSUE THREAD

**Issue by MageJohn** [SecUpwN/Spotify-AdKiller#83]
Hey!

I've been using the dns-block branch for a little while. I noticed that playlist covers were getting blocked, even custom ones I'd set myself. A quick look at various terminal outputs seemed to indicate that blocking u.scdn.co was the culprit. I whitelisted that in dns-block.c and recompiled, and the issue seems to be fixed. I'll report back if unwanted things are now unblocked. Should this be added to the repository code?

**Comment by OlegSmelov** [comment]
Use it for a day or two, and if you see no problems with ads, please create a pull request. Thanks!

**Comment by MageJohn** [comment]
Okay, I've been using it with no problems for a few days now. Will make a pull request now. :-)

**Comment by OlegSmelov** [comment]
Merged.
