### ISSUE TITLE
Save files from stream

### ISSUE THREAD

**Issue by apiraino** [SecUpwN/Spotify-AdKiller#85]
Hi all,

I'm preparing a small patch to use `arecord` to save audio files. Are you interested in that?

In case you do, I'd like to patch master with the `dns-block` branch already merged in. Is it possibile?

Thank you!

Cheers

**Comment by OlegSmelov** [comment]
I think this functionality belongs to a separate project. You are welcome to fork `Spotify-AdKiller` and reuse as much code as possible.
